// Option lists for the "Manage Business" section in Settings.

export const BUSINESS_TYPES = ['Retailer', 'Wholesaler', 'Distributor', 'Manufacturer', 'Services'];

export const REGISTRATION_TYPES = [
  'Private Limited Company',
  'Public Limited Company',
  'Partnerships Firm',
  'Limited Liability Partnership',
  'One Person Company',
  'Sole Proprietorship',
  'Section 8 Company',
  'Hindu Undivided Family',
  'Trust / Society',
  'Not Registered',
];

export const INDUSTRY_TYPES = [
  'Accounting and Financial Services',
  'Agriculture',
  'Automobile',
  'Battery',
  'Broadband / Cable / Internet',
  'Building Material and Construction',
  'Cleaning and Pest Control',
  'Consulting',
  'Dairy (Milk)',
  'Doctor / Clinic / Hospital',
  'Education (Coaching / School)',
  'Electrical Works',
  'Electronics',
  'Engineering',
  'Event Planning and Management',
  'FMCG Products',
  'Fitness / Sports',
  'Footwear',
  'Fruits and Vegetables',
  'Furniture',
  'Garment / Clothing',
  'General Store (Kirana)',
  'Gift Shop',
  'Hardware Store',
  'Hotel / Restaurant / Cafe',
  'Interior Designer',
  'IT / Software',
  'Jewellery and Gems',
  'Kirana / Grocery',
  'Machinery',
  'Meat',
  'Medical / Pharmacy',
  'Mobile and Accessories',
  'Oil and Gas',
  'Packaging',
  'Paper and Stationery',
  'Photography',
  'Plastic Products',
  'Printing',
  'Real Estate',
  'Salon / Spa',
  'Scrap',
  'Security / Housekeeping',
  'Steel / Metal',
  'Tailoring / Boutique',
  'Textiles',
  'Tours and Travels',
  'Transport and Logistics',
  'Handicrafts / Handmade',
  'Other',
];
